const KEY="omnipocket.v1";
const defaults={settings:{baseCurrency:"NGN",theme:"dark",privacyHidden:false,mode:"hybrid"},accounts:[],transactions:[],goals:[]};
let state=load();let quickType="income";const $=id=>document.getElementById(id);
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return JSON.parse(JSON.stringify(defaults))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function money(value,currency){currency=currency||state.settings.baseCurrency;try{return new Intl.NumberFormat(undefined,{style:"currency",currency:currency,maximumFractionDigits:2}).format(value)}catch{return currency+" "+Number(value).toLocaleString()}}
const rates={NGN:{NGN:1,USD:1/1500,GBP:1/2020,EUR:1/1750},USD:{NGN:1500,USD:1,GBP:2020/1500,EUR:1750/1500},GBP:{NGN:2020,USD:1500/2020,GBP:1,EUR:1750/2020},EUR:{NGN:1750,USD:1500/1750,GBP:2020/1750,EUR:1}};
function convert(v,from,to){if(from===to)return Number(v)||0;return (Number(v)||0)*((rates[from]&&rates[from][to])||1)}
function netWorth(){return state.accounts.reduce((s,a)=>s+convert(a.balance,a.currency,state.settings.baseCurrency),0)}
function render(){ $("netWorth").textContent=state.settings.privacyHidden?"•••••••":money(netWorth());$("baseCurrencyButton").textContent=state.settings.baseCurrency+" · Base currency";$("accountCount").textContent=state.accounts.length+" account"+(state.accounts.length===1?"":"s");$("syncState").textContent=state.settings.mode==="offline"?"Offline":"Local-first";renderAccounts();renderActivity();renderGoal()}
function renderAccounts(){var el=$("accountList");if(!state.accounts.length){el.innerHTML="<div class=empty-state>No money nodes yet. Add your first account.</div>";return}el.innerHTML=state.accounts.filter(a=>!a.archived).slice(0,5).map(a=>"<div class=account-row><div class=account-main><span class=node>◉</span><div class=truncate><div>"+a.name+"</div><div class=muted>"+a.currency+" · "+a.type+"</div></div></div><span class=amount>"+(state.settings.privacyHidden?"••••":money(a.balance,a.currency))+"</span></div>").join("")}
function renderActivity(){var el=$("activityList"),rows=state.transactions.slice().sort((a,b)=>b.createdAt-a.createdAt).slice(0,5);if(!rows.length){el.innerHTML="<div class=empty-state>Transactions will appear here.</div>";return}el.innerHTML=rows.map(t=>{var sign=t.direction==="out"?"−":t.direction==="in"?"+":"";return "<div class=activity-row><div><div>"+(t.label||t.type)+"</div><div class=muted>"+t.date+" · "+(t.accountName||"")+"</div></div><span class=amount>"+sign+money(t.amount,t.currency)+"</span></div>"}).join("")}
function renderGoal(){var el=$("goalContent"),g=state.goals.find(x=>x.status!=="completed");if(!g){el.innerHTML=state.goals.length?"<div class=empty-state>All goals completed. Create another target.</div>":"<div class=empty-state>Create your first financial target.</div>";return}var current=g.accountIds.reduce((s,id)=>{var a=state.accounts.find(x=>x.id===id);return s+(a?convert(a.balance,a.currency,g.currency):0)},0);var pct=Math.min(100,g.target?current/g.target*100:0);el.innerHTML="<strong>"+g.name+"</strong><div class=muted>"+money(current,g.currency)+" of "+money(g.target,g.currency)+"</div><div style=\"height:10px;background:rgba(255,255,255,.08);border-radius:99px;margin:14px 0 8px;overflow:hidden\"><div style=\"width:"+pct+"%;height:100%;background:var(--primary);border-radius:inherit\"></div></div><div class=muted>"+pct.toFixed(0)+"%"+(g.deadline?" · Deadline "+g.deadline:"")+"</div>"}
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+"-"+Math.random()}
function populateAccounts(){$("quickAccount").innerHTML=state.accounts.filter(a=>!a.archived).map(a=>"<option value=\""+a.id+"\">"+a.name+" · "+a.currency+"</option>").join("")}
function openQuick(type){quickType=type;$("quickTitle").textContent={income:"Add money",expense:"Spend",transfer:"Transfer",adjustment:"Adjust"}[type]||"Quick entry";$("quickCategoryWrap").style.display=type==="expense"?"grid":"none";populateAccounts();$("quickDate").value=new Date().toISOString().slice(0,10);$("quickDialog").showModal()}
$("fab").onclick=()=>openQuick("expense");document.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>openQuick(b.dataset.quick));$("addAccountButton").onclick=()=>$("accountDialog").showModal();
$("accountForm").addEventListener("submit",e=>{e.preventDefault();state.accounts.push({id:uid(),name:$("accountName").value.trim(),institution:$("accountInstitution").value.trim(),type:$("accountType").value,currency:$("accountCurrency").value,balance:Number($("accountBalance").value)||0,archived:false,createdAt:Date.now()});save();$("accountDialog").close();e.target.reset()});
$("quickForm").addEventListener("submit",e=>{e.preventDefault();var a=state.accounts.find(x=>x.id===$("quickAccount").value);if(!a)return;var amount=Math.abs(Number($("quickAmount").value)||0);if(!amount)return;if(quickType==="adjustment")a.balance=amount;else if(quickType==="expense")a.balance-=amount;else if(quickType==="income")a.balance+=amount;else{alert("Transfer workflow is next.");return}state.transactions.push({id:uid(),type:quickType,direction:quickType==="expense"?"out":"in",amount:amount,currency:a.currency,accountId:a.id,accountName:a.name,label:quickType==="expense"?$("quickCategory").value:quickType,date:$("quickDate").value||new Date().toISOString().slice(0,10),note:$("quickNote").value.trim(),createdAt:Date.now(),status:"recorded"});save();$("quickDialog").close();e.target.reset()});
$("privacyButton").onclick=()=>{state.settings.privacyHidden=!state.settings.privacyHidden;save()};
$("baseCurrencyButton").onclick=()=>{var next=(prompt("Base currency (NGN, USD, GBP, EUR):",state.settings.baseCurrency)||"").toUpperCase();if(["NGN","USD","GBP","EUR"].includes(next)){state.settings.baseCurrency=next;save()}};
$("addGoalButton").onclick=()=>{if(!state.accounts.length){alert("Add an account first.");return}var name=prompt("Goal name:");if(!name)return;var target=Number(prompt("Target amount:","100000"))||0;var currency=(prompt("Goal currency:",state.settings.baseCurrency)||state.settings.baseCurrency).toUpperCase();state.goals.push({id:uid(),name:name,target:target,currency:currency,accountIds:state.accounts.map(a=>a.id),deadline:"",status:"active",createdAt:Date.now()});save()};
window.addEventListener("load",()=>{if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("sw.js");render()});